sudo: required
language: java
jdk:
 - openjdk12
services:
    - docker
env:
    global:
        - TAG=$(git describe --abbrev=0)
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
    - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service-account --key-file service-account.json
    - gcloud config set project spring-cloud-k8s-285204
    - gcloud config set compute/zone us-central1-c
    - gcloud container clusters get-credentials spring-cloud-k8s
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin	

script:
    - cd config-server
    - mvn install -Djasypt.encryptor.password=${JASYPT_PASS}
    - cd ..
    - (cd users-commons; mvn install)
    - mvn install:install-file -Dfile=users-commons/target/users-commons-0.0.1-SNAPSHOT.jar -DgroupId=com.jdiaz.users.commons -DartifactId=users-commons -Dversion=0.0.1-SNAPSHOT -Dpackaging=jar
    - (cd users-service; mvn install)
    - (cd auth-server; mvn install)
    - (cd eureka-server; mvn install)
    - (cd zuul-server; mvn install)

deploy:
    provider: script
    script: bash ./deploy.sh
    on:
        branch: master